# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: imagebuilding
trigger:
- main

variables:
- group: <enter variable group name>

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    containerRegistry: '<enter service connection name>'
    repository: '$(repo)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(imagetag)'